# stream_to_hdfs_and_mongo.py
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, from_json
from pyspark.sql.types import StructType, StructField, StringType

# --- 1. Spark Session with MongoDB Configuration ---
# We must include the MongoDB URI pointing to your specific IP (192.168.15.121)
spark = SparkSession.builder \
    .appName("KafkaToHdfsAndMongo") \
    .config("spark.mongodb.write.connection.uri", "mongodb://192.168.15.121:27017/portaria_db.web_events") \
    .getOrCreate()

spark.sparkContext.setLogLevel("WARN")

# --- 2. Define the Schema ---
json_schema = StructType([
    StructField("event_id", StringType(), True),
    StructField("source", StringType(), True),
    StructField("timestamp", StringType(), True)
])

# --- 3. Read Stream from Kafka ---
print("[INFO] Connecting to Kafka cluster at 192.168.15.115...")
kafka_df = spark.readStream \
    .format("kafka") \
    .option("kafka.bootstrap.servers", "192.168.15.115:9092,192.168.15.115:9093,192.168.15.115:9094") \
    .option("subscribe", "cluster-topic") \
    .option("startingOffsets", "earliest") \
    .load()

# --- 4. Transform Data ---
parsed_df = kafka_df.selectExpr("CAST(value AS STRING) as json_string") \
    .select(from_json(col("json_string"), json_schema).alias("data")) \
    .select("data.*")

# --- 5. The ForeachBatch Function (The Multiplexer) ---
def write_to_multiple_sinks(batch_df, batch_id):
    """
    This function is executed for every micro-batch generated by the stream.
    batch_df is a static DataFrame representing the data in this specific batch.
    """
    print(f"[INFO] Processing Micro-Batch ID: {batch_id}")
    
    # We use persist() because we are going to write this same batch twice. 
    # This prevents Spark from recalculating the Kafka read twice.
    batch_df.persist()
    
    if batch_df.count() > 0:
        # A. Write to HDFS (Cold Storage for History)
        HDFS_TARGET_DIR = "/datalake/silver/web_events"
        batch_df.write \
            .format("parquet") \
            .mode("append") \
            .save(HDFS_TARGET_DIR)
        print(f" -> Successfully saved batch {batch_id} to HDFS.")

        # B. Write to MongoDB (Hot Storage for the Application)
        batch_df.write \
            .format("mongodb") \
            .mode("append") \
            .save()
        print(f" -> Successfully saved batch {batch_id} to MongoDB.")
    
    # Release the memory
    batch_df.unpersist()

# --- 6. Start the Stream ---
print("[INFO] Starting hybrid stream to HDFS and MongoDB...")
HDFS_CHECKPOINT_DIR = "/datalake/silver/web_events/_hybrid_checkpoints"

query = parsed_df.writeStream \
    .foreachBatch(write_to_multiple_sinks) \
    .option("checkpointLocation", HDFS_CHECKPOINT_DIR) \
    .start()

query.awaitTermination()
